### ISSUE TITLE
Create RT emulator library.

### ISSUE THREAD

**Issue by jgomezdans** [multiply-org/data-access#4]
We need an RT emulator library, which needs to be done. At the moment, we only have e.g. PROSAIL, but we might need to add other models.

**Comment by TonioF** [comment]
There is a deliverable on Prototype Emulators which is due by the end of June. I guess that's a good due date for this issue.  Do you agree?

**Comment by jgomezdans** [comment]
:+1:  on this. One thing I'd like to maybe flag is the format of the emulator library. In [gp_emulator](https://github.com/multiply-org/gp_emulator/blob/62f288792e1b24a12891fc0ad32896cb7cb5eda4/gp_emulator/multivariate_gp.py#L100), the skeleton of the format is there (using hdf5 but commented out). I'll try to draft some notes on what's needed and data structures, but it'd be good @TonioF  to have a look at those.

**Comment by jgomezdans** [comment]
Moved to [gp_emulator](https://github.com/multiply-org/gp_emulator/wiki/Emulator-library-design-notes)
